config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  #devise_for :users, :controllers => {sessions: 'sessions'}
  root :to => "welcome#index"
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/_user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    #include DeviseTokenAuth::Concerns::User
    has_many :comments, dependent: :destroy
    belongs_to :user
    validates :title, presence: true, length: { minimum: 5 }
    validates :text, presence: true
    
    def to_array
        {
            "id" => self.id,
            "title" => self.title,
            "text" => self.text,
            "user_id" => self.user.id,
            "comments" => self.comments 
        }
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    #include DeviseTokenAuth::Concerns::User
    belongs_to :article
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  before_save -> { skip_confirmation! }
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  has_many :articles
  has_many :coments
  include DeviseTokenAuth::Concerns::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  #protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #before_action :authenticate_user!, except: [:index, :show]
    
    def show
        @article = Article.find(params[:id])
        render json: @article 
    end

    def index
        @articles = Article.all
        response = @articles.map(&:to_array)
        render json: response 
    end

    def create
        @article = Article.new(article_params)

        if(user_signed_in?)
            @article.user = current_user
        else
            render json: {'msj' => 'unauthorized'}, status: :unauthorized
            return
        end
    
        if(@article.save)
            render json: @article, status: :created
            return
        else
            render json: @article.errors, status: :bad_request
            return
        end
    end

    def update
        @article = Article.find(params[:id])

        if(!user_signed_in?)
            render json: {'msj' => 'unauthorized'}, status: :unauthorized
            return
        else
            if (@article.user.id != current_user.id)
                render json: {'msj' => 'forbiddent'}, status: :forbidden
                return
            end
        end
        
        if @article.update(article_params)
            render json: @article, status: :created
        else
            render json: @article.errors, status: :bad_request
        end
    end

    def destroy
        @article = Article.find(params[:id])
        if(!user_signed_in?)
            render json: {'msj' => 'unauthorized'}, status: :unauthorized
            return
        else
            if (@article.user.id != current_user.id)
                render json: {'msj' => 'forbiddent'}, status: :forbidden
                return
            end
        end
        @article.destroy
        
        head :no_content
    end

  private
    def article_params
        params.require(:article).permit(:title, :text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    if(!user_signed_in?)
        render json: {'msj' => 'unauthorized'}, status: :unauthorized
        return
    else
        @comment = @article.comments.create(comment_params)
        @comment.user = current_user
        if(@comment.save)
            render json: @comment, status: :created
            return
        else
            render json: @comment.errors, status: :bad_request
            return
        end
    end
    
    render json: @comment, status: :created
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if(!user_signed_in?)
        render json: {'msj' => 'unauthorized'}, status: :unauthorized
        return
    else
        if (@article.user.id != current_user.id)
            render json: {'msj' => 'forbiddent'}, status: :forbidden
            return
        end
    end
    @comment.destroy
    head :no_content
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/frontend_controller.rb
class FrontendController < ActionController::Base
  #include DeviseTokenAuth::Concerns::SetUserByToken
  #protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < FrontendController
  def index
    render "index", layout: "application"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="header">
  <h1 class="text-muted">Articulos</h1>
  <div>
    <%= link_to 'Nuevo', new_article_path, {:class => "btn btn-lg btn-success"} %>
  </div>
</div>
<br>

<div>
  <div class="row panel panel-primary">
    <div class="clearfix panel-heading">
      <div class="col-sm-6" >Titulo</div>
      <div class="col-sm-6" ></div>
    </div>
  </div>
 
<% @articles.each do |article| %>
  <div class="row panel panel-default">
    <div class="panel-body col-sm-6" ><%= article.title %></div>
    <div class="panel-body col-sm-6" >
      <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), article_path(article), :style => 'float:right;',
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_article_path(article), {:style => 'float:right;'} %>
      <%= link_to raw('<span class="glyphicon glyphicon-eye-open"></span>'), article_path(article), :style => 'float:right;' %>
    </div>
  </div>
<% end %>
</div>

app/views/articles/new.html.erb
<div class="header">
  <h1 class="text-muted">Nuevo Articulo</h1>
  <div>
    <%= link_to 'Back', articles_path, {:class => "btn btn-lg btn-success"} %>
  </div>
</div>
<br>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-muted">
  <%= @article.title %>
</h1>
 
<p  class="lead" >
  <%= @article.text %>
</p>
<ln/>
<h3 class="text-muted">Comentarios</h3>
<%= render @article.comments %>
<ln/>
<h3 class="text-muted">Agregar Comentario:</h3>
<%= render "comments/form" %>

<%= link_to 'Back', articles_path %> | <%= link_to 'Edit', edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<div class="row panel panel-default">
  <div class="panel-budy col-sm-2"><p class="lead"><%= comment.commenter %></p></div>
  <div class="panel-budy col-sm-4"><p class="lead"><%= comment.body %></p></div>
  <div class="panel-budy col-sm-2"><p>
    <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </p></div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello Rails!!!</h1>
<p class="lead">Esto es una prueba de Ruby on Rails, se trata de un blog muy muy muy sencillo con un CRUD de Articulos y comentarios y un sistema de autenticacíon muy básico.</p>
<%= link_to 'Empezar', {:controller => 'articles', :action => 'index'},{:class => "btn btn-lg btn-success"} %>